# Generated by Django 5.2 on 2025-06-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('On Hold', 'On Hold')], default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='mastersetting',
            name='category',
            field=models.CharField(choices=[('Channel', 'Channel'), ('Country', 'Country'), ('Person', 'Person'), ('Case Category', 'Case Category'), ('Series', 'Series'), ('Material', 'Material'), ('Case Sub-Category', 'Case Sub-Category')], max_length=50),
        ),
    ]
