# Generated by Django 5.2 on 2025-06-01 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_complaint_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='case_type',
        ),
        migrations.AddField(
            model_name='complaint',
            name='case_category',
            field=models.ForeignKey(limit_choices_to={'category': 'Case Category'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_case_category', to='management.mastersetting'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='case_sub_category',
            field=models.ForeignKey(limit_choices_to={'category': 'Case Sub-Category'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_case_sub_category', to='management.mastersetting'),
        ),
    ]
