# Generated by Django 5.2 on 2025-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_complaint_case_type_complaint_case_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='action_from_factory',
            field=models.TextField(blank=True, default='Not Provided', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_description',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='justification_from_factory',
            field=models.TextField(blank=True, default='Not Provided', null=True),
        ),
    ]
