# Generated by Django 5.2 on 2025-06-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_complaint_action_from_factory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='channel',
            field=models.ForeignKey(default='Whatsapp', limit_choices_to={'category': 'Channel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_channel', to='management.mastersetting'),
        ),
    ]
