# Generated by Django 5.2 on 2025-06-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_complaint_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
