# Generated by Django 5.2 on 2025-06-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_mastersetting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersetting',
            name='category',
            field=models.CharField(choices=[('Channel', 'Channel'), ('Country', 'Country'), ('Person', 'Person'), ('Case Category', 'Case Category'), ('Series', 'Series'), ('Material', 'Material'), ('Type', 'Type'), ('Region', 'Region')], max_length=50),
        ),
    ]
