# Generated by Django 5.2 on 2025-06-23 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_mastersetting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='region',
            field=models.ForeignKey(limit_choices_to={'category': 'Region'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='management.mastersetting'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='case_category',
            field=models.ForeignKey(limit_choices_to={'category': 'Category'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_case_category', to='management.mastersetting'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='case_sub_category',
            field=models.ForeignKey(limit_choices_to={'category': 'Type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_case_sub_category', to='management.mastersetting'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='person',
            field=models.ForeignKey(limit_choices_to={'category': 'Reported By'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_person', to='management.mastersetting'),
        ),
        migrations.AlterField(
            model_name='mastersetting',
            name='category',
            field=models.CharField(choices=[('Channel', 'Channel'), ('Country', 'Country'), ('Reported By', 'Reported By'), ('Category', 'Category'), ('Type', 'Type'), ('Series', 'Series'), ('Material', 'Material'), ('Region', 'Region')], max_length=50),
        ),
    ]
