# Generated by Django 5.2 on 2025-06-23 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_sku_region_alter_complaint_case_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus_by_region', to='management.mastersetting'),
        ),
    ]
