# Generated by Django 5.2 on 2025-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_complaint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='cad_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
